name: Build and Push (seedvr2)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute dynamic tags
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "DATE_TAG=$(date -u +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Free disk space
        run: |
          df -h
          sudo rm -rf /usr/local/lib/android || true
          sudo rm -rf /usr/share/dotnet || true
          sudo rm -rf /opt/ghc || true
          sudo rm -rf /opt/hostedtoolcache || true
          docker system prune -af || true
          df -h

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          load: false
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/worker-comfyui-seedvr2:seedvr2
            ${{ secrets.DOCKERHUB_USERNAME }}/worker-comfyui-seedvr2:sha-${{ env.SHORT_SHA }}
            ${{ secrets.DOCKERHUB_USERNAME }}/worker-comfyui-seedvr2:run-${{ github.run_number }}
            ${{ secrets.DOCKERHUB_USERNAME }}/worker-comfyui-seedvr2:${{ env.DATE_TAG }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/worker-comfyui-seedvr2:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/worker-comfyui-seedvr2:buildcache,mode=max
