name: Build & publish RunPod worker
on:
  push:
    branches: [ main ]       # or whatever branch you deploy from

env:
  IMAGE_NAME: runpod-worker-comfy-custom
  REGISTRY: ghcr.io/${{ github.repository_owner }}

permissions:
  contents: read
  packages: write            # needed for ghcr

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v5      # BuildKit
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          platforms: linux/amd64
